name: dotnet package
on:
  push:
    branches:
      - main # Default release branch
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1.8.1
        with:
          #dotnet-version: '3.1.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/Digitalroot-Valheim/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_PAT}}
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "üñ•Ô∏è The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: List files in the src repository
        run: |
          ls ${{ github.workspace }}/src
      - name: List files in the src/Digitalroot.Valheim.Common.Log repository
        run: |
          ls ${{ github.workspace }}/src/Digitalroot.Valheim.Common.Log           
      - run: echo "üçè This job's status is ${{ job.status }}."
      - run: dotnet build --configuration Release src/Digitalroot.Valheim.Common.Log/Digitalroot.Valheim.Common.Log.csproj
      - name: Create the package
        run: dotnet pack --configuration Release src/Digitalroot.Valheim.Common.Log/Digitalroot.Valheim.Common.Log.csproj
      - name: Publish the package to GPR
        run: dotnet nuget push src/Digitalroot.Valheim.Common.Log/bin/Release/*.nupkg --skip-duplicate
